

GET https://493jj1jomk.execute-api.eu-west-2.amazonaws.com/prod/football
###

POST https://493jj1jomk.execute-api.eu-west-2.amazonaws.com/prod/football
content-type: application/json

{
  "name": "Dale"
}
###

