

GET https://493jj1jomk.execute-api.eu-west-2.amazonaws.com/prod/football
###

DELETE https://493jj1jomk.execute-api.eu-west-2.amazonaws.com/prod/football?id=37fbefb1-2e72-4454-a078-8df1ced5dc84
###

POST https://493jj1jomk.execute-api.eu-west-2.amazonaws.com/prod/football
content-type: application/json

{
  "name": "Dale"
}
###

PUT https://493jj1jomk.execute-api.eu-west-2.amazonaws.com/prod/football?id=e3b73f0a-d961-4f11-bc28-8b496d77edd9
content-type: application/json

{
  "name": "HOUSE"
}
###
